import CoreData

final class CoreDataStack: @unchecked Sendable {
    static let shared = CoreDataStack()

    let container: NSPersistentContainer

    private init() {
        container = NSPersistentContainer(name: "NovaMart")
        container.loadPersistentStores { description, error in
            if let error {
                // In production, surface this to crash reporting before fatalError
                fatalError("CoreData failed to load: \(error.localizedDescription)")
            }
            description.shouldMigrateStoreAutomatically = true
            description.shouldInferMappingModelAutomatically = true
        }
        container.viewContext.automaticallyMergesChangesFromParent = true
        container.viewContext.mergePolicy = NSMergePolicy.mergeByPropertyObjectTrump
    }

    var viewContext: NSManagedObjectContext { container.viewContext }

    func newBackgroundContext() -> NSManagedObjectContext {
        let ctx = container.newBackgroundContext()
        ctx.mergePolicy = NSMergePolicy.mergeByPropertyObjectTrump
        return ctx
    }

    func save(context: NSManagedObjectContext? = nil) {
        let ctx = context ?? viewContext
        guard ctx.hasChanges else { return }
        do {
            try ctx.save()
        } catch {
            ctx.rollback()
        }
    }

    func performBackgroundTask<T: Sendable>(_ block: @Sendable @escaping (NSManagedObjectContext) throws -> T) async throws -> T {
        try await container.performBackgroundTask { ctx in
            ctx.mergePolicy = NSMergePolicy.mergeByPropertyObjectTrump
            let result = try block(ctx)
            if ctx.hasChanges { try ctx.save() }
            return result
        }
    }
}

// MARK: - Managed object subclass stubs (generated at build time from .xcdatamodel)

// CDProduct, CDCartItem, CDOrder, CDUser, CDWishlistItem, CDSearchHistory, CDAddress
// are auto-generated by Xcode from the NovaMart.xcdatamodeld model file.
// The model defines:
//
// CDProduct:       id(UUID), name, brand, price(Decimal), imageURL, isFavourite, timestamp
// CDCartItem:      id(UUID), productID, variantID, quantity(Int), addedAt
// CDOrder:         id(UUID), orderNumber, statusRaw, total(Decimal), createdAt
// CDUser:          id(UUID), name, email, phone, loyaltyPoints(Int), tierRaw, createdAt
// CDWishlistItem:  productID(UUID), addedAt
// CDSearchHistory: query, timestamp
// CDAddress:       id(UUID), label, line1, line2, city, state, zip, country, isDefault
